---
- name: Delete PyYAML
  shell: "{{ item }}"
  loop:
    - "rm -rf {{ fts_venv }}/lib/python3.11/site-packages/yaml"
    - "rm -rf {{ fts_venv }}/lib/python3.11/site-packages/PyYAML-*"

- name: Install apt packages
  apt:
    name: "{{ fts_ui_apt_packages }}"

- name: "Install pip packages"
  pip:
    name: "{{ fts_ui_pip_packages }}"
    virtualenv: "{{ fts_venv }}"

- name: "Install {{ fts_ui_pip_package_name }} from git"
  pip:
    name: "{{ fts_ui_git_requirement }}"
    virtualenv: "{{ fts_venv }}"
  when: fts_ui_git_requirement | default('') | length > 0

- name: "Install {{ fts_ui_pip_package_name }} from PyPI"
  pip:
    name: "{{ fts_ui_pip_package_name }}"
    virtualenv: "{{ fts_venv }}"
  when: fts_ui_git_requirement | default('') | length == 0
