---
- name: Delete PyYAML
  shell: "{{ item }}"
  loop:
    - "rm -rf {{ fts_python_packages }}/site-packages/yaml"
    - "rm -rf {{ fts_python_packages }}/site-packages/PyYAML-*"

- name: Install apt dependencies
  apt:
    name: "{{ fts_apt_dependencies | list }}"

- name: "Install {{ fts_pip_package_name }} from git ({{ fts_git_requirement }})"
  pip:
    name: "{{ fts_git_requirement }}"
    virtualenv: "{{ fts_venv }}"
  when: fts_git_requirement | default('') | length > 0

- name: "Install {{ fts_pip_package_name }} from PyPI"
  pip:
    name: "{{ fts_pip_package_name }}=={{ fts_version }}"
    virtualenv: "{{ fts_venv }}"
  when: fts_git_requirement | default('') | length == 0
